services:
  itemcatalogdb:
    container_name: itemcatalogdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ItemCatalogDb
    ports:
      - "5433:5432"
    volumes:
      - itemcatalogdb_data:/var/lib/postgresql

  authservicedb:
    container_name: authservicedb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=AuthServiceDb
    ports:
      - "5434:5432"
    volumes:
      - authservicedb_data:/var/lib/postgresql

  itemcatalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__ItemCatalogDb=Server=itemcatalogdb;Port=5432;Database=ItemCatalogDb;Username=postgres;Password=postgres;Include Error Detail=true
    depends_on:
      - itemcatalogdb
    ports:
      - "6050:8080"
      - "6150:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  authservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__AuthServiceDb=Server=authservicedb;Port=5432;Database=AuthServiceDb;Username=postgres;Password=postgres;Include Error Detail=true
    depends_on:
      - authservicedb
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  yarpapigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - JwtOptions__Authority=http://authservice.api:8080
      - ReverseProxy__Clusters__itemcatalog-cluster__Destinations__destination1__Address=http://itemcatalog.api:8080
      - ReverseProxy__Clusters__authservice-cluster__Destinations__destination1__Address=http://authservice.api:8080
    depends_on:
      - itemcatalog.api
      - authservice.api
    ports:
      - "7050:8080"
      - "7150:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
